export const FORGOT_PASSWORD_REQUEST = 'app/ForgotPassword/FORGOT_PASSWORD_REQUEST';
export const FORGOT_PASSWORD_SUCCESS = 'app/ForgotPassword/FORGOT_PASSWORD_SUCCESS';
export const FORGOT_PASSWORD_ERROR = 'app/ForgotPassword/FORGOT_PASSWORD_ERROR';
